# Generated by Django 3.0.4 on 2020-03-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200324_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agree',
            field=models.BooleanField(default=True, verbose_name='Соглашение про отправку уведомлений на почту'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Мужской пол'), (2, 'Женский пол')], default=1, verbose_name='Пол'),
        ),
    ]
