# Generated by Django 3.0.4 on 2020-03-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
