# Generated by Django 3.0.4 on 2020-03-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200325_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='default@mail.com', max_length=200),
        ),
    ]
