# Generated by Django 3.0.4 on 2020-03-25 22:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20200325_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='user.email', max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='user_images', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
    ]
