# Generated by Django 3.0.4 on 2020-03-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200325_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='user.email', max_length=200, verbose_name='Email'),
        ),
    ]
