# Generated by Django 3.0.4 on 2020-03-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='personal_info',
        ),
    ]
