# Generated by Django 3.0.4 on 2020-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200320_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Мужской пол'), (2, 'Женский пол')], default=1, verbose_name='Пол'),
        ),
    ]
